FROM golang:1.22.0-alpine3.19 as dependencies

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

FROM dependencies AS build
COPY . ./
RUN CGO_ENABLED=0 go build -o /main -ldflags="-w -s" ./cmd/app/
WORKDIR /go/src/
RUN go install github.com/go-delve/delve/cmd/dlv@master

FROM tihmmm/golang-alpine-rootless:go-1.22.0-alp-3.19
COPY --chown=user:user --chmod=550 --from=build /main /home/user/main
COPY --chown=user:user --chmod=550 --from=build /go/bin/dlv /home/user/dlv
WORKDIR /home/user/
COPY --chown=user:user ./FPRU_crit.sh ./FPRU_crit.sh
COPY --chown=user:user ./FPRU_high.sh ./FPRU_high.sh

CMD ["/home/user/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "/home/user/main"]